// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © lao_sha

//@version=5
indicator("Lao_Sha_KDJ",overlay = false)
ilong = input.int(9, title='period')
isig = input.int(3, title='signal')
bcwsma(s, l, m) =>
    _bcwsma = float(na)
    _s = s
    _l = l
    _m = m
    _bcwsma := (_m * _s + (_l - _m) * nz(_bcwsma[1])) / _l
    _bcwsma
c = close
h = ta.highest(high, ilong)
l = ta.lowest(low, ilong)
RSV = 100 * ((c - l) / (h - l))
pK = bcwsma(RSV, isig, 1)
pD = bcwsma(pK, isig, 1)
pJ = 3 * pK - 2 * pD
KDJ = math.avg(pD, pJ, pK)
plot(pK, title='% K', color=color.new(color.orange, 0))
plot(pD, title='% D', color=color.new(color.lime, 0))
plot(pJ, title='% J', color=color.new(color.fuchsia, 0))
// plot(KDJ, title='KDJ', color=color.new(color.white, 0))
h1=hline(30,color =color.new( color.red,50),linestyle = hline.style_dotted)
h2=hline(70,color = color.new(color.blue,50),linestyle = hline.style_dotted)
fill(h1,h2,color =color.new(color.blue,90))
