// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © lao_sha

//@version=5
indicator("Lao_Sha_dmi",overlay = false)
diLength = input.int(15)
adxSmoothing=input.int(20)
[diplus,diminus,adx]=ta.dmi(diLength, adxSmoothing)
p1=plot(diplus, title='% K', color=color.new(color.orange, 0))
p2=plot(diminus, title='% D', color=color.new(color.lime, 0))
// plot(adx, title='% J', color=color.new(color.fuchsia, 0))
color colorDmi =diplus>diminus?color.new(color.green,90):color.new(color.red,90)
fill(p1,p2,color=colorDmi)
